### ISSUE TITLE
Error: Handling missing provider

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/europeana-qa-spark#6]
The error message:

```
16-05-11 10:33:49 ERROR JsonUtils: Unhandled object type: java.util.LinkedHashMap, [record ID: 08541/10442_01_75365, path: $.['ore:Aggregation'][0]['edm:dataProvider'][0]]
16-05-11 10:33:49 ERROR Executor: Exception in task 239.0 in stage 0.0 (TID 247)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at com.nsdr.spark.completeness.CompletenessCalculator.calculate(CompletenessCalculator.java:68)
```

**Comment by pkiraly** [comment]
The fix solved the issue.
